# Site settings
title: Naqib Rahimi
subtitle: Ph.D. Candidate
email: Naqib.Rahimy123@gmail.com
url: https://github.com/jeromelachaud/freelancer-theme
# description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
# keywords: "your keywords, separated by commas"
skills: "Computational Mechanics, Fluid-Structure Interaction, Air-Blast-Structure Interaction\n"
methods: "Smoothed Particle Hydrodynamics (SPH), Peridynamics, Phase-field, IGA, FEM"
meta_author: Rahimi Naqib

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: Naqib

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 80B3FF #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary-rgb: "24,21,21" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Naqib Rahimi
  location: 
  social: 
  # credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/naqibr
  - title: google scholar
    url: https://scholar.google.com/citations?user=eoyEQ3kAAAAJ&hl=en&oi=ao
  - title: linkedin
    url: https://www.linkedin.com/in/naqib-rahimi?original_referer=https%3A%2F%2Fwww.google.com%2F
  - title: researchgate
    url: https://www.researchgate.net/profile/M-Naqib-Rahimi
  - title: instagram
    url: https://www.instagram.com/naqib_rahimi

# Postal address (add as many lines as necessary)
address:
  - line: 1212 Old computer science building
  - line: Stony Brook University, New York 11794

# Credits content
# credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

host: 127.0.0.1
port: 4000
livereload: true

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""

