# site settings
title: Naqib Rahimi
subtitle: Ph.D. Candidate
email: Naqib.Rahimy123@gmail.com
description: Discover My Work
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Naqib Rahimi
street_address: 1212 Old computer science building, Stony Brook University
city: Stony Brook
state: New York
zip_code: 11794
country: United States of America
phone: (631) 384-4156

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/naqibr
  GitLab:
  Google-Plus:
  Instagram: https://www.instagram.com/naqib_rahimi
  LinkedIn: https://www.linkedin.com/in/naqib-rahimi?original_referer=https%3A%2F%2Fwww.google.com%2F
  ResearchGate: https://www.researchgate.net/profile/M-Naqib-Rahimi
  Twitter:
  Facebook:
  Slack:
  Google-Scholar: https://scholar.google.com/citations?user=eoyEQ3kAAAAJ&hl=en&oi=ao

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
